### Get all suppliers
GET {{Forge.Api_HostAddress}}/api/suppliers

### Get supplier by ID
GET {{Forge.Api_HostAddress}}/api/suppliers/1

### Create supplier
POST {{Forge.Api_HostAddress}}/api/suppliers
Content-Type: application/json

{
  "name": "Supplier A",
  "currency": "PHP",
  "contactPerson": "Juan Dela Cruz",
  "contactEmail": "juan@suppliera.com",
  "contactPhone": "09171234567"
}

### Update supplier
PUT {{Forge.Api_HostAddress}}/api/suppliers/1
Content-Type: application/json

{
  "name": "Supplier A Updated",
  "currency": "PHP",
  "contactPerson": "Juan Dela Cruz",
  "contactEmail": "juan@suppliera.com",
  "contactPhone": "09171234567"
}

### Deactivate supplier
DELETE {{Forge.Api_HostAddress}}/api/suppliers/1